### ISSUE TITLE
Wildcard serialize, get and set, doesn't apply to getter properties ~5

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-map-define#4]
From: https://github.com/canjs/canjs/issues/1730

http://jsbin.com/cefaza/3/edit?js,console

Getter properties don't get serialized when `serialize` is set ike this:

```
'*': {
  serialize: true
}
```
## getter / setter

From: https://github.com/canjs/canjs/issues/2367

Trying to use the define plugin getters & setters on the 'wildcard' / 'default' property results in unexpected behaviour. 

eg.

``` js
define: {
    '*': {
        set: function(value) {
            return JSON.stringify(value);
        },
        get: function (value) {
            return JSON.parse(value);
        }
    }
}
```

When any setter is defined an error is thrown, when a getter is defined it simply isn't called. 

The repo below shows how the getter isn't applied. To reproduce the setter issue, uncomment the setter.
https://github.com/nlundquist/canjs-default-setter 

If this is an expected incompatibility we might want to add a note in the docs.

**Comment by phillipskevin** [comment]
Inadvertently closed without realizing this issue now covers wildcard get and set and not just wildcard serialize. Only wildcard serialize has been fixed.

**Comment by justinbmeyer** [comment]
Closing.  Will accept patches if someone submits one.
