### ISSUE TITLE
Should define support nullable and required properties?

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-map-define#8]
[This was originally incorrectly filed as can-define issue #20]

Currently in can-map-define, setting a `Type` attribute on a property ensures that after setting that property using `.attr()`, the property's value will be an instance of that `Type` class, even if the value passed to `.attr()`  is `null` or `undefined`.  The property's value starts as `undefined` if neither `Value` nor `value` is set, but once set, the only way to get a "null value" (`null` or `undefined`) for that property is to use `.removeAttr()`.

Likewise, setting `Value` or `value` enforces an initial value, but does not resist nor reset to default if `removeAttr()` is called for the property; the result is a value of `undefined`.

I think that it would be helpful to have slightly better type/value enforcement options.  Since sometimes we want to have a `Maybe<Map>` (as static-type functional programmers call it) where a property is assumed to have either an object of the parameter type or a null value, it may be sensible to allow for something like `nullable: true` as a define attribute.  This would prevent implicitly calling the constructor if the value is a null value.

Conversely, if users wanted to guarantee that a property always had a particular value, it would make sense to have a `required: true` attribute, which either disables `.removeAttr()` or follows it up with a call to the appropriate `Value` or `value` constructor.

Does this seem like a good idea?

**Comment by justinbmeyer** [comment]
I think some of this issue will be closed by: https://github.com/canjs/canjs/issues/2316.  Anyway you can update the issue to reflect things you'd like to see outside of that issue?

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-define #173](https://github.com/canjs/can-define/issues/173) via [**ZenHub**](https://www.zenhub.com/)
